version: "3.8"
services:
  postgres:
    hostname: postgres
    image: postgres:12
    command: [ "postgres", "-c", "log_statement=all" ] # log all queries
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: manager
    ports:
      - "5432:5432"
  wallet:
    build:
      context: .
      dockerfile: ./.docker/images/dev/Dockerfile
    command: poetry run uvicorn wallet.app:app --host=0.0.0.0 --port 8000 --reload --http h11 --loop uvloop --log-level info
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./migrations:/app/migrations
      - ./tests:/app/tests
      - ./wallet:/app/wallet
volumes:
  pg: